# Generated by Django 4.2.6 on 2023-11-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeimage',
            name='number',
        ),
        migrations.AddField(
            model_name='homeimage',
            name='name',
            field=models.CharField(default='image', max_length=50),
        ),
    ]
